{{- $arch := .chezmoi.arch -}}
{{- if eq $arch "amd64" }}{{ $arch = "x86_64" }}{{ end -}}
[".local/bin/redu"]
  type = "file"
  url = {{ gitHubLatestReleaseAssetURL "drdo/redu" (printf "redu-*-linux-%s.bz2" $arch) | quote }}
  filter.command = "bzip2"
  filter.args = ["-d"]
  executable = true
