[".config/zsh/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting"
    refreshPeriod = "168h"
[".config/zsh/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-vi-mode"]
    type = "git-repo"
    url = "https://github.com/jeffreytse/zsh-vi-mode"
    refreshPeriod = "168h"
